### PR TITLE
close echos with $ansi_std that start with $ansi_white

### PR DESCRIPTION
**Pull request by ProBackup-nl**
Otherwise the command prompt becomes $ansi_white too inadvertently.

### CODE REVIEW

**Comment by zyxmon** [comment]
Can you give an example of this bug?

**Comment by ProBackup-nl** [comment]
It' an edge case. I was on the terminal, trying to start daemontools. As soon as the init script contains a command like "`exec </dev/null;exec >/dev/null;exec 2>/dev/null;`" (sourced from daemontools its svscanboot), it will happen that terminal output stops at: "Starting daemontools..."  and returns to prompt in color white.

**Comment by ryzhovau** [comment]
Thanks for report. This PR will be applied to Entware-ng.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/rtndev/commit/45481e6b52f6c350f2d6c47eac16ce284ee398d4

**Pull request closed without merging**
